# highlighter: pygments
highlighter: rouge

# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://jungblo.github.io/
devurl: http://localhost:4000/
name: 째깍악어
title: 째깍악어 기술 블로그
description: "째깍악어 기술블로그"

my:
    displayName: 째깍악어
    realName: 째깍악어스
    realName_cn: 째깍이
    jobTitle: "Coder"
    contact:
        qq: 000
        email: jungblo@tictoccroc.com
        github: http://www.github.com/jungblo
        qzone: http://744910240.qzone.qq.com
        pinterest: https://www.pinterest.com/miblah/
        tel: 000
        address:
            country: 123
            state: 123
            city: 123
            distribute: 123
            postcode: 000000
            cell: "어디어디"
    skills:
        frontend: ["HTML", "CSS", "JS | jQuery", "Bootstrap", "React Native"]
        backend: ["PHP", "Python", "Shell", MySQL", "DJango"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll", "Vscode"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
